[tool.poetry]
name = "hydrogym"
version = "0.1"
authors = [
    "Jared Callaham <jared.callaham@gmail.com>",
    "Ludger Paehler <ludger.paehler@tum.de>",
    "Sam Ahnert <sammahnert@gmail.com>",
]
description = "A Reinforcement Learning Benchmarking Environment for Fluid Dynamics"
license = "LICENSE"
readme = "README.md"
classifiers=[
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: Unix",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Topic :: Scientific/Engineering :: Hydrology",
    "Topic :: Scientific/Engineering :: Physics",
]
documentation = "https://hydrogym.readthedocs.io/"
repository = "https://github.com/dynamicslab/hydrogym"
include = [
    { path = "hydrogym"}
]
exclude = [
    "hydrogym/firedrake/*"
]

[tool.poetry.dependencies]
control = "^0.9.2"
dmsuite = "^0.1.1"
evotorch = "^0.3.0"
gmsh = "^4.11.1"
gym = "^0.26.2"
modred = "^2.1.0"
python = "^3.8"
torch = "1.13"  # Needs to be fixed to 1.13

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
